<?php

namespace Database\Seeders;

use App\Models\Setting;
use Illuminate\Database\Seeder;

class SettingsSeeder extends Seeder
{
    public function run(): void
    {
        $settings = [
            // General Settings
            [
                'key' => 'site_name',
                'value' => 'نظام إدارة التعلم',
                'group' => 'general',
                'type' => 'text',
                'label' => 'اسم الموقع',
                'description' => 'اسم الموقع الذي يظهر في العنوان والشعار',
                'is_public' => true,
            ],
            [
                'key' => 'site_description',
                'value' => 'نظام متكامل لإدارة العملية التعليمية',
                'group' => 'general',
                'type' => 'textarea',
                'label' => 'وصف الموقع',
                'description' => 'وصف مختصر للموقع يظهر في محركات البحث',
                'is_public' => true,
            ],
            [
                'key' => 'site_logo',
                'value' => null,
                'group' => 'general',
                'type' => 'file',
                'label' => 'شعار الموقع',
                'description' => 'شعار الموقع (يفضل PNG بخلفية شفافة)',
                'is_public' => true,
            ],
            [
                'key' => 'site_favicon',
                'value' => null,
                'group' => 'general',
                'type' => 'file',
                'label' => 'أيقونة الموقع',
                'description' => 'أيقونة الموقع التي تظهر في تبويب المتصفح',
                'is_public' => true,
            ],
            [
                'key' => 'default_language',
                'value' => 'ar',
                'group' => 'general',
                'type' => 'select',
                'options' => ['ar' => 'العربية', 'en' => 'English'],
                'label' => 'اللغة الافتراضية',
                'description' => 'اللغة الافتراضية للموقع',
                'is_public' => true,
            ],
            [
                'key' => 'timezone',
                'value' => 'Asia/Riyadh',
                'group' => 'general',
                'type' => 'select',
                'options' => [
                    'Asia/Riyadh' => 'توقيت الرياض (GMT+3)',
                    'Asia/Dubai' => 'توقيت دبي (GMT+4)',
                    'Africa/Cairo' => 'توقيت القاهرة (GMT+2)',
                    'Asia/Kuwait' => 'توقيت الكويت (GMT+3)',
                    'Asia/Bahrain' => 'توقيت البحرين (GMT+3)',
                ],
                'label' => 'المنطقة الزمنية',
                'description' => 'المنطقة الزمنية للموقع',
                'is_public' => false,
            ],
            [
                'key' => 'maintenance_mode',
                'value' => '0',
                'group' => 'general',
                'type' => 'boolean',
                'label' => 'وضع الصيانة',
                'description' => 'تفعيل وضع الصيانة يمنع الوصول للموقع',
                'is_public' => false,
            ],
            [
                'key' => 'registration_enabled',
                'value' => '1',
                'group' => 'general',
                'type' => 'boolean',
                'label' => 'السماح بالتسجيل',
                'description' => 'السماح للمستخدمين الجدد بالتسجيل',
                'is_public' => true,
            ],

            // Contact Settings
            [
                'key' => 'contact_email',
                'value' => 'info@example.com',
                'group' => 'contact',
                'type' => 'email',
                'label' => 'البريد الإلكتروني',
                'description' => 'البريد الإلكتروني للتواصل',
                'is_public' => true,
            ],
            [
                'key' => 'contact_phone',
                'value' => '+966 50 000 0000',
                'group' => 'contact',
                'type' => 'text',
                'label' => 'رقم الهاتف',
                'description' => 'رقم الهاتف للتواصل',
                'is_public' => true,
            ],
            [
                'key' => 'contact_address',
                'value' => 'الرياض، المملكة العربية السعودية',
                'group' => 'contact',
                'type' => 'textarea',
                'label' => 'العنوان',
                'description' => 'عنوان المؤسسة',
                'is_public' => true,
            ],
            [
                'key' => 'google_maps_url',
                'value' => '',
                'group' => 'contact',
                'type' => 'text',
                'label' => 'رابط خرائط جوجل',
                'description' => 'رابط الموقع على خرائط جوجل',
                'is_public' => true,
            ],

            // Social Media
            [
                'key' => 'social_twitter',
                'value' => '',
                'group' => 'social',
                'type' => 'text',
                'label' => 'تويتر (X)',
                'description' => 'رابط حساب تويتر',
                'is_public' => true,
            ],
            [
                'key' => 'social_facebook',
                'value' => '',
                'group' => 'social',
                'type' => 'text',
                'label' => 'فيسبوك',
                'description' => 'رابط صفحة فيسبوك',
                'is_public' => true,
            ],
            [
                'key' => 'social_instagram',
                'value' => '',
                'group' => 'social',
                'type' => 'text',
                'label' => 'انستقرام',
                'description' => 'رابط حساب انستقرام',
                'is_public' => true,
            ],
            [
                'key' => 'social_linkedin',
                'value' => '',
                'group' => 'social',
                'type' => 'text',
                'label' => 'لينكدإن',
                'description' => 'رابط صفحة لينكدإن',
                'is_public' => true,
            ],
            [
                'key' => 'social_youtube',
                'value' => '',
                'group' => 'social',
                'type' => 'text',
                'label' => 'يوتيوب',
                'description' => 'رابط قناة يوتيوب',
                'is_public' => true,
            ],

            // Email Settings
            [
                'key' => 'mail_from_name',
                'value' => 'نظام إدارة التعلم',
                'group' => 'email',
                'type' => 'text',
                'label' => 'اسم المرسل',
                'description' => 'الاسم الذي يظهر كمرسل للبريد',
                'is_public' => false,
            ],
            [
                'key' => 'mail_from_address',
                'value' => 'noreply@example.com',
                'group' => 'email',
                'type' => 'email',
                'label' => 'بريد المرسل',
                'description' => 'عنوان البريد الإلكتروني للإرسال',
                'is_public' => false,
            ],
            [
                'key' => 'smtp_host',
                'value' => 'smtp.mailtrap.io',
                'group' => 'email',
                'type' => 'text',
                'label' => 'خادم SMTP',
                'description' => 'عنوان خادم البريد SMTP',
                'is_public' => false,
            ],
            [
                'key' => 'smtp_port',
                'value' => '587',
                'group' => 'email',
                'type' => 'number',
                'label' => 'منفذ SMTP',
                'description' => 'رقم منفذ خادم SMTP',
                'is_public' => false,
            ],
            [
                'key' => 'smtp_username',
                'value' => '',
                'group' => 'email',
                'type' => 'text',
                'label' => 'اسم المستخدم SMTP',
                'description' => 'اسم المستخدم للمصادقة',
                'is_public' => false,
            ],
            [
                'key' => 'smtp_password',
                'value' => '',
                'group' => 'email',
                'type' => 'text',
                'label' => 'كلمة مرور SMTP',
                'description' => 'كلمة المرور للمصادقة',
                'is_public' => false,
            ],
            [
                'key' => 'smtp_encryption',
                'value' => 'tls',
                'group' => 'email',
                'type' => 'select',
                'options' => ['tls' => 'TLS', 'ssl' => 'SSL', 'null' => 'بدون تشفير'],
                'label' => 'نوع التشفير',
                'description' => 'نوع تشفير الاتصال',
                'is_public' => false,
            ],

            // Notification Settings
            [
                'key' => 'notify_new_user',
                'value' => '1',
                'group' => 'notifications',
                'type' => 'boolean',
                'label' => 'إشعار المستخدم الجديد',
                'description' => 'إرسال إشعار عند تسجيل مستخدم جديد',
                'is_public' => false,
            ],
            [
                'key' => 'notify_new_enrollment',
                'value' => '1',
                'group' => 'notifications',
                'type' => 'boolean',
                'label' => 'إشعار التسجيل الجديد',
                'description' => 'إرسال إشعار عند تسجيل طالب في دورة',
                'is_public' => false,
            ],
            [
                'key' => 'notify_new_ticket',
                'value' => '1',
                'group' => 'notifications',
                'type' => 'boolean',
                'label' => 'إشعار تذكرة جديدة',
                'description' => 'إرسال إشعار عند إنشاء تذكرة دعم جديدة',
                'is_public' => false,
            ],
            [
                'key' => 'notify_session_reminder',
                'value' => '1',
                'group' => 'notifications',
                'type' => 'boolean',
                'label' => 'تذكير بالجلسات',
                'description' => 'إرسال تذكير قبل الجلسات المباشرة',
                'is_public' => false,
            ],
            [
                'key' => 'session_reminder_minutes',
                'value' => '30',
                'group' => 'notifications',
                'type' => 'number',
                'label' => 'وقت التذكير (دقائق)',
                'description' => 'عدد الدقائق قبل الجلسة لإرسال التذكير',
                'is_public' => false,
            ],

            // Security Settings
            [
                'key' => 'password_min_length',
                'value' => '8',
                'group' => 'security',
                'type' => 'number',
                'label' => 'الحد الأدنى لكلمة المرور',
                'description' => 'الحد الأدنى لعدد أحرف كلمة المرور',
                'is_public' => false,
            ],
            [
                'key' => 'require_email_verification',
                'value' => '1',
                'group' => 'security',
                'type' => 'boolean',
                'label' => 'تأكيد البريد الإلكتروني',
                'description' => 'طلب تأكيد البريد الإلكتروني للمستخدمين الجدد',
                'is_public' => false,
            ],
            [
                'key' => 'session_lifetime',
                'value' => '120',
                'group' => 'security',
                'type' => 'number',
                'label' => 'مدة الجلسة (دقائق)',
                'description' => 'مدة صلاحية جلسة المستخدم بالدقائق',
                'is_public' => false,
            ],
            [
                'key' => 'max_login_attempts',
                'value' => '5',
                'group' => 'security',
                'type' => 'number',
                'label' => 'محاولات تسجيل الدخول',
                'description' => 'الحد الأقصى لمحاولات تسجيل الدخول الفاشلة',
                'is_public' => false,
            ],
            [
                'key' => 'lockout_duration',
                'value' => '15',
                'group' => 'security',
                'type' => 'number',
                'label' => 'مدة الحظر (دقائق)',
                'description' => 'مدة حظر تسجيل الدخول بعد تجاوز المحاولات',
                'is_public' => false,
            ],
            [
                'key' => 'two_factor_enabled',
                'value' => '0',
                'group' => 'security',
                'type' => 'boolean',
                'label' => 'المصادقة الثنائية',
                'description' => 'تفعيل المصادقة الثنائية للمستخدمين',
                'is_public' => false,
            ],

            // Zoom Settings
            [
                'key' => 'zoom_sdk_key',
                'value' => '',
                'group' => 'zoom',
                'type' => 'text',
                'label' => 'مفتاح Zoom SDK',
                'description' => 'مفتاح SDK من حساب Zoom',
                'is_public' => false,
            ],
            [
                'key' => 'zoom_sdk_secret',
                'value' => '',
                'group' => 'zoom',
                'type' => 'text',
                'label' => 'Zoom SDK Secret',
                'description' => 'المفتاح السري لـ Zoom SDK',
                'is_public' => false,
            ],
            [
                'key' => 'zoom_account_id',
                'value' => '',
                'group' => 'zoom',
                'type' => 'text',
                'label' => 'معرف حساب Zoom',
                'description' => 'معرف حساب Zoom للـ API',
                'is_public' => false,
            ],
            [
                'key' => 'zoom_client_id',
                'value' => '',
                'group' => 'zoom',
                'type' => 'text',
                'label' => 'Zoom Client ID',
                'description' => 'معرف عميل Zoom',
                'is_public' => false,
            ],
            [
                'key' => 'zoom_client_secret',
                'value' => '',
                'group' => 'zoom',
                'type' => 'text',
                'label' => 'Zoom Client Secret',
                'description' => 'المفتاح السري لعميل Zoom',
                'is_public' => false,
            ],
        ];

        foreach ($settings as $setting) {
            Setting::updateOrCreate(
                ['key' => $setting['key']],
                $setting
            );
        }
    }
}
