<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\ActivityLog;
use App\Models\XapiStatement;
use App\Models\SatisfactionSurvey;
use App\Models\Ticket;
use App\Models\TeacherRating;
use App\Models\Attendance;
use App\Models\User;
use App\Models\Program;
use App\Models\Session;
use App\Models\Enrollment;

class NelcComplianceController extends Controller
{
    public function dashboard()
    {
        $stats = [
            'total_students' => User::where('role', 'student')->count(),
            'total_teachers' => User::where('role', 'teacher')->count(),
            'total_programs' => Program::count(),
            'total_sessions' => Session::count(),
            'total_activities' => ActivityLog::count(),
            'xapi_sent' => XapiStatement::where('status', 'sent')->count(),
            'xapi_pending' => XapiStatement::where('status', 'pending')->count(),
            'surveys_count' => SatisfactionSurvey::count(),
            'tickets_resolved' => Ticket::where('status', 'resolved')->count(),
            'attendance_records' => Attendance::count(),
            'teacher_ratings' => TeacherRating::count(),
            'active_enrollments' => Enrollment::where('status', 'active')->count(),
        ];

        // Calculate compliance percentage
        $standards = $this->getStandards();
        $total = count($standards);
        $implemented = collect($standards)->where('status', 'implemented')->count();
        $partial = collect($standards)->where('status', 'partial')->count();
        $complianceScore = round((($implemented + ($partial * 0.5)) / $total) * 100);

        return view('admin.nelc.dashboard', compact('stats', 'standards', 'complianceScore', 'total', 'implemented', 'partial'));
    }

    private function getStandards(): array
    {
        return [
            // === القسم 1: المتطلبات المؤسسية ===
            // 1.1 السياسات والتنظيم
            [
                'code' => '1.1.1',
                'title_ar' => 'وجود استراتيجية معتمدة للجهة متضمنة التعليم الإلكتروني',
                'category' => 'السياسات والتنظيم',
                'type' => 'اختياري',
                'status' => 'implemented',
                'link' => route('admin.dashboard'),
                'link_label' => 'لوحة التحكم',
                'notes' => 'النظام يدعم التعليم الإلكتروني بالكامل',
            ],
            [
                'code' => '1.1.2',
                'title_ar' => 'توفر خطة لإدارة المخاطر واستمرارية العملية التعليمية',
                'category' => 'السياسات والتنظيم',
                'type' => 'اختياري',
                'status' => 'implemented',
                'link' => route('nelc.policies.risk-management'),
                'link_label' => 'خطة إدارة المخاطر',
                'notes' => 'صفحة سياسة منشورة',
            ],
            [
                'code' => '1.1.3',
                'title_ar' => 'التقيد بالأنظمة واللوائح والسياسات الوطنية',
                'category' => 'السياسات والتنظيم',
                'type' => 'إلزامي',
                'status' => 'implemented',
                'link' => route('nelc.policies.national-compliance'),
                'link_label' => 'صفحة الالتزام',
                'notes' => 'تعهد بالالتزام منشور',
            ],
            [
                'code' => '1.1.4',
                'title_ar' => 'الالتزام بتحقيق النزاهة الأكاديمية',
                'category' => 'السياسات والتنظيم',
                'type' => 'إلزامي',
                'status' => 'implemented',
                'link' => route('nelc.policies.academic-integrity'),
                'link_label' => 'سياسة النزاهة',
                'notes' => 'سياسة النزاهة الأكاديمية منشورة',
            ],
            [
                'code' => '1.1.5',
                'title_ar' => 'الالتزام بمبادئ حقوق الملكية الفكرية',
                'category' => 'السياسات والتنظيم',
                'type' => 'إلزامي',
                'status' => 'implemented',
                'link' => route('nelc.policies.intellectual-property'),
                'link_label' => 'سياسة الملكية الفكرية',
                'notes' => 'سياسة حقوق الملكية الفكرية منشورة',
            ],
            [
                'code' => '1.1.6',
                'title_ar' => 'الالتزام بسياسات ومبادئ أخلاقيات الذكاء الاصطناعي',
                'category' => 'السياسات والتنظيم',
                'type' => 'إلزامي',
                'status' => 'implemented',
                'link' => route('nelc.policies.ai-ethics'),
                'link_label' => 'سياسة أخلاقيات AI',
                'notes' => 'سياسة أخلاقيات الذكاء الاصطناعي منشورة',
            ],
            [
                'code' => '1.1.7',
                'title_ar' => 'الالتزام بضمان خصوصية بيانات المستفيدين وحمايتها',
                'category' => 'السياسات والتنظيم',
                'type' => 'إلزامي',
                'status' => 'implemented',
                'link' => route('nelc.policies.privacy'),
                'link_label' => 'سياسة الخصوصية',
                'notes' => 'سياسة الخصوصية وحماية البيانات منشورة',
            ],
            [
                'code' => '1.1.8',
                'title_ar' => 'توفر هيكل تنظيمي يحدد أدوار ومسؤوليات القائمين',
                'category' => 'السياسات والتنظيم',
                'type' => 'إلزامي',
                'status' => 'implemented',
                'link' => route('admin.users.index'),
                'link_label' => 'إدارة المستخدمين',
                'notes' => 'أدوار واضحة: مدير، معلم، طالب مع صلاحيات Spatie',
            ],
            [
                'code' => '1.1.9',
                'title_ar' => 'وجود سياسة للحضور تضمن احتساب الحضور الإلكتروني',
                'category' => 'السياسات والتنظيم',
                'type' => 'إلزامي',
                'status' => 'implemented',
                'link' => route('nelc.policies.attendance'),
                'link_label' => 'سياسة الحضور',
                'notes' => 'سياسة الحضور + نظام تتبع الحضور',
            ],
            [
                'code' => '1.1.10',
                'title_ar' => 'وضوح سياسة التواصل للمستفيدين',
                'category' => 'السياسات والتنظيم',
                'type' => 'إلزامي',
                'status' => 'implemented',
                'link' => route('nelc.policies.communication'),
                'link_label' => 'سياسة التواصل',
                'notes' => 'سياسة التواصل + نظام تذاكر الدعم',
            ],
            [
                'code' => '1.1.11',
                'title_ar' => 'توفر آلية لمتابعة أداء المتعلمين',
                'category' => 'السياسات والتنظيم',
                'type' => 'إلزامي',
                'status' => 'implemented',
                'link' => route('admin.activity-logs.index'),
                'link_label' => 'سجل النشاطات',
                'notes' => 'تتبع شامل للنشاطات + تقارير الأداء',
            ],

            // 1.2 البنية التقنية
            [
                'code' => '1.2.1',
                'title_ar' => 'توفر البنية التقنية اللازمة لتنفيذ برامج التعليم الإلكتروني',
                'category' => 'البنية التقنية',
                'type' => 'إلزامي',
                'status' => 'implemented',
                'link' => route('admin.dashboard'),
                'link_label' => 'لوحة التحكم',
                'notes' => 'Laravel 12 + MySQL + Zoom + xAPI',
            ],
            [
                'code' => '1.2.2',
                'title_ar' => 'توفر نظام دخول موحد وآمن (SSO)',
                'category' => 'البنية التقنية',
                'type' => 'اختياري',
                'status' => 'implemented',
                'link' => route('login'),
                'link_label' => 'صفحة الدخول',
                'notes' => 'FutureX SSO + Nafath + نظام مصادقة موحد',
            ],
            [
                'code' => '1.2.3',
                'title_ar' => 'توفر نظام للتحقق من هوية المستفيد',
                'category' => 'البنية التقنية',
                'type' => 'إلزامي',
                'status' => 'implemented',
                'link' => route('login'),
                'link_label' => 'نظام التحقق',
                'notes' => 'Nafath (هوية وطنية) + OTP + تحقق ثنائي',
            ],
            [
                'code' => '1.2.4',
                'title_ar' => 'توفر نظام إدارة تعلم (LMS)',
                'category' => 'البنية التقنية',
                'type' => 'إلزامي',
                'status' => 'implemented',
                'link' => route('admin.dashboard'),
                'link_label' => 'نظام إدارة التعلم',
                'notes' => 'نظام LMS متكامل مع كل الأدوات المطلوبة',
            ],
            [
                'code' => '1.2.5',
                'title_ar' => 'توفر نظام للفصول الافتراضية',
                'category' => 'البنية التقنية',
                'type' => 'إلزامي',
                'status' => 'implemented',
                'link' => route('admin.sessions.index'),
                'link_label' => 'الجلسات / Zoom',
                'notes' => 'تكامل Zoom كامل مع تسجيل وحضور',
            ],
            [
                'code' => '1.2.6',
                'title_ar' => 'توفر أنظمة تحليل البيانات',
                'category' => 'البنية التقنية',
                'type' => 'اختياري',
                'status' => 'implemented',
                'link' => route('admin.reports.index'),
                'link_label' => 'التقارير والإحصائيات',
                'notes' => 'لوحات بيانات + تقارير + Chart.js',
            ],
            [
                'code' => '1.2.7',
                'title_ar' => 'توفر تطبيق على الأجهزة الذكية',
                'category' => 'البنية التقنية',
                'type' => 'اختياري',
                'status' => 'not_implemented',
                'link' => '#',
                'link_label' => 'غير متوفر حالياً',
                'notes' => 'يمكن تطويره مستقبلاً (PWA أو Native)',
            ],
            [
                'code' => '1.2.8',
                'title_ar' => 'توفر خاصية البحث عن المحتويات الرقمية',
                'category' => 'البنية التقنية',
                'type' => 'اختياري',
                'status' => 'implemented',
                'link' => route('admin.subjects.index'),
                'link_label' => 'البحث في المقررات',
                'notes' => 'بحث متقدم في المحتوى والمقررات',
            ],
            [
                'code' => '1.2.9',
                'title_ar' => 'دعم وصول ذوي الإعاقة',
                'category' => 'البنية التقنية',
                'type' => 'اختياري',
                'status' => 'partial',
                'link' => route('nelc.policies.accessibility'),
                'link_label' => 'سياسة إمكانية الوصول',
                'notes' => 'بنية تحتية جاهزة + حقول alt_text + تباين الألوان',
            ],
            [
                'code' => '1.2.10',
                'title_ar' => 'توظيف المستحدثات التقنية (AI)',
                'category' => 'البنية التقنية',
                'type' => 'اختياري',
                'status' => 'partial',
                'link' => route('admin.xapi.index'),
                'link_label' => 'xAPI / تحليلات التعلم',
                'notes' => 'xAPI + تحليلات التعلم + إمكانية إضافة AI',
            ],
            [
                'code' => '1.2.11',
                'title_ar' => 'توفر أداة لقياس رضا المستفيدين',
                'category' => 'البنية التقنية',
                'type' => 'إلزامي',
                'status' => 'implemented',
                'link' => route('admin.surveys.index'),
                'link_label' => 'الاستبيانات',
                'notes' => 'نظام استبيانات كامل مع مقياس خماسي',
            ],
            [
                'code' => '1.2.12',
                'title_ar' => 'دعم مختلف الأجهزة وأنظمة التشغيل',
                'category' => 'البنية التقنية',
                'type' => 'إلزامي',
                'status' => 'implemented',
                'link' => route('home'),
                'link_label' => 'الموقع الرئيسي',
                'notes' => 'تصميم متجاوب TailwindCSS يدعم جميع الأجهزة',
            ],

            // 1.3 الدعم والتدريب
            [
                'code' => '1.3.1',
                'title_ar' => 'تطوير مهارات منسوبي الجهة في التعليم الإلكتروني',
                'category' => 'الدعم والتدريب',
                'type' => 'إلزامي',
                'status' => 'implemented',
                'link' => '#',
                'link_label' => 'تعهد بالالتزام',
                'notes' => 'تعهد بتوفير تدريب وشهادات معتمدة',
            ],
            [
                'code' => '1.3.2',
                'title_ar' => 'توفر تعليمات للمتعلم وعضو هيئة التدريس',
                'category' => 'الدعم والتدريب',
                'type' => 'إلزامي',
                'status' => 'implemented',
                'link' => route('nelc.guides.student'),
                'link_label' => 'الأدلة الإرشادية',
                'notes' => 'دليل الطالب + دليل المعلم',
            ],
            [
                'code' => '1.3.3',
                'title_ar' => 'توفير تعليمات واضحة عن الدعم الفني',
                'category' => 'الدعم والتدريب',
                'type' => 'إلزامي',
                'status' => 'implemented',
                'link' => route('nelc.policies.technical-support'),
                'link_label' => 'صفحة الدعم الفني',
                'notes' => 'نظام تذاكر + صفحة دعم فني',
            ],
            [
                'code' => '1.3.4',
                'title_ar' => 'ضمان حصول المتعلم على الإرشاد الأكاديمي',
                'category' => 'الدعم والتدريب',
                'type' => 'إلزامي',
                'status' => 'implemented',
                'link' => '#',
                'link_label' => 'تعهد بالالتزام',
                'notes' => 'تعهد بتقديم الإرشاد الأكاديمي طوال مدة البرنامج',
            ],

            // === القسم 2: المتطلبات البرامجية ===
            // 2.1 المحتوى الرقمي
            [
                'code' => '2.1.1',
                'title_ar' => 'توفر محتوى رقمي مرتبط بالمقرر وأهدافه',
                'category' => 'المحتوى الرقمي',
                'type' => 'إلزامي',
                'status' => 'implemented',
                'link' => route('admin.subjects.index'),
                'link_label' => 'إدارة المقررات',
                'notes' => 'محتوى كامل على نظام إدارة التعلم',
            ],
            [
                'code' => '2.1.2',
                'title_ar' => 'توفر المحتوى بأشكال مختلفة (نصوص، سمعية، مرئية)',
                'category' => 'المحتوى الرقمي',
                'type' => 'إلزامي',
                'status' => 'implemented',
                'link' => route('admin.sessions.index'),
                'link_label' => 'الجلسات والملفات',
                'notes' => 'فيديو + ملفات PDF + صوت + نصوص',
            ],
            [
                'code' => '2.1.3',
                'title_ar' => 'ضمان جودة تصميم المحتوى الرقمي',
                'category' => 'المحتوى الرقمي',
                'type' => 'إلزامي',
                'status' => 'implemented',
                'link' => route('home'),
                'link_label' => 'واجهة النظام',
                'notes' => 'تصميم عالي الجودة TailwindCSS',
            ],
            [
                'code' => '2.1.4',
                'title_ar' => 'توفر أنشطة تعليمية متنوعة',
                'category' => 'المحتوى الرقمي',
                'type' => 'إلزامي',
                'status' => 'implemented',
                'link' => route('admin.sessions.index'),
                'link_label' => 'الأنشطة والاختبارات',
                'notes' => 'اختبارات + واجبات + مشاريع + مناقشات',
            ],
            [
                'code' => '2.1.5',
                'title_ar' => 'إتاحة محتوى مفتوح من البرنامج',
                'category' => 'المحتوى الرقمي',
                'type' => 'إلزامي',
                'status' => 'implemented',
                'link' => route('nelc.open-content'),
                'link_label' => 'المحتوى المفتوح',
                'notes' => 'صفحة محتوى تعليمي مفتوح للجميع',
            ],
            [
                'code' => '2.1.6',
                'title_ar' => 'توفر تصميم وهيكلة موحدة لجميع الوحدات',
                'category' => 'المحتوى الرقمي',
                'type' => 'إلزامي',
                'status' => 'implemented',
                'link' => route('admin.subjects.index'),
                'link_label' => 'قوالب المقررات',
                'notes' => 'قوالب Blade موحدة لجميع المقررات',
            ],
            [
                'code' => '2.1.7',
                'title_ar' => 'تقسيم المحتوى إلى أجزاء صغيرة (Chunking)',
                'category' => 'المحتوى الرقمي',
                'type' => 'إلزامي',
                'status' => 'implemented',
                'link' => route('admin.sessions.index'),
                'link_label' => 'الوحدات والجلسات',
                'notes' => 'محتوى مقسم: برامج > مقررات > وحدات > جلسات',
            ],
            [
                'code' => '2.1.9',
                'title_ar' => 'عرض المحتوى بطريقة منظمة تسهل التنقل',
                'category' => 'المحتوى الرقمي',
                'type' => 'إلزامي',
                'status' => 'implemented',
                'link' => route('admin.programs.index'),
                'link_label' => 'هيكلة البرامج',
                'notes' => 'تنقل واضح ومنظم بين المحتوى',
            ],
            [
                'code' => '2.1.10',
                'title_ar' => 'توافق تصميم المحتوى مع معايير xAPI',
                'category' => 'المحتوى الرقمي',
                'type' => 'اختياري',
                'status' => 'implemented',
                'link' => route('admin.xapi.index'),
                'link_label' => 'لوحة xAPI',
                'notes' => 'تكامل xAPI كامل مع LRS',
            ],

            // 2.2 تصميم البرنامج
            [
                'code' => '2.2.1',
                'title_ar' => 'توفر وصف واضح للبرنامج التعليمي',
                'category' => 'تصميم البرنامج',
                'type' => 'إلزامي',
                'status' => 'implemented',
                'link' => route('admin.programs.index'),
                'link_label' => 'وصف البرامج',
                'notes' => 'وصف كامل ثنائي اللغة لكل برنامج',
            ],
            [
                'code' => '2.2.2',
                'title_ar' => 'تمكين المتعلم من معرفة مدى إنجازه',
                'category' => 'تصميم البرنامج',
                'type' => 'اختياري',
                'status' => 'implemented',
                'link' => route('admin.reports.student-progress'),
                'link_label' => 'تقدم الطلاب',
                'notes' => 'تتبع تقدم الطالب + نسبة الإنجاز',
            ],
            [
                'code' => '2.2.5',
                'title_ar' => 'توفر تقييم ذاتي مع تغذية راجعة فورية',
                'category' => 'تصميم البرنامج',
                'type' => 'إلزامي',
                'status' => 'implemented',
                'link' => route('admin.subjects.index'),
                'link_label' => 'الاختبارات الذاتية',
                'notes' => 'نظام اختبارات مع محاولات متعددة وتغذية راجعة',
            ],
            [
                'code' => '2.2.6',
                'title_ar' => 'تقديم التغذية الراجعة باستمرار',
                'category' => 'تصميم البرنامج',
                'type' => 'إلزامي',
                'status' => 'implemented',
                'link' => route('admin.subjects.index'),
                'link_label' => 'نظام التقييمات',
                'notes' => 'تغذية راجعة للواجبات والاختبارات',
            ],

            // 2.3 المتطلبات
            [
                'code' => '2.3.1',
                'title_ar' => 'تحديد المتطلبات المعرفية للالتحاق بالمقرر',
                'category' => 'متطلبات الالتحاق',
                'type' => 'إلزامي',
                'status' => 'implemented',
                'link' => route('admin.subjects.index'),
                'link_label' => 'متطلبات المقررات',
                'notes' => 'نظام prerequisites للمقررات',
            ],
            [
                'code' => '2.3.2',
                'title_ar' => 'ضمان الوصول العادل لجميع المتعلمين',
                'category' => 'متطلبات الالتحاق',
                'type' => 'إلزامي',
                'status' => 'implemented',
                'link' => route('nelc.policies.accessibility'),
                'link_label' => 'سياسة إمكانية الوصول',
                'notes' => 'محتوى سمعي وبصري + تفريغ نصي',
            ],

            // 2.4 التقييم والتحسين
            [
                'code' => '2.4.2',
                'title_ar' => 'توفر سياسة واضحة لتقييم الأنشطة والمهام',
                'category' => 'التقييم والتحسين',
                'type' => 'إلزامي',
                'status' => 'implemented',
                'link' => route('nelc.policies.assessment'),
                'link_label' => 'سياسة التقييم',
                'notes' => 'سياسة تقييم منشورة مع توزيع الدرجات',
            ],
            [
                'code' => '2.4.4',
                'title_ar' => 'تنوع أدوات التقييم',
                'category' => 'التقييم والتحسين',
                'type' => 'إلزامي',
                'status' => 'implemented',
                'link' => route('admin.subjects.index'),
                'link_label' => 'أدوات التقييم',
                'notes' => 'اختبارات + واجبات + مشاريع + مشاركة',
            ],
            [
                'code' => '2.4.6',
                'title_ar' => 'مراجعة وتقويم المحتوى الرقمي',
                'category' => 'التقييم والتحسين',
                'type' => 'إلزامي',
                'status' => 'implemented',
                'link' => '#',
                'link_label' => 'تعهد بالالتزام',
                'notes' => 'تعهد بمراجعة المحتوى دورياً',
            ],
            [
                'code' => '2.4.7',
                'title_ar' => 'تمكين المتعلم من تقييم المحتوى الرقمي',
                'category' => 'التقييم والتحسين',
                'type' => 'اختياري',
                'status' => 'implemented',
                'link' => route('admin.surveys.index'),
                'link_label' => 'استبيانات التقييم',
                'notes' => 'نظام استبيانات لتقييم المحتوى',
            ],
            [
                'code' => '2.4.9',
                'title_ar' => 'تقييم أعضاء هيئة التدريس',
                'category' => 'التقييم والتحسين',
                'type' => 'إلزامي',
                'status' => 'implemented',
                'link' => route('admin.teacher-ratings.index'),
                'link_label' => 'تقييم المعلمين',
                'notes' => 'نظام تقييم متعدد الأبعاد للمعلمين',
            ],
            [
                'code' => '2.4.11',
                'title_ar' => 'توفير بيانات مفتوحة لدعم الأبحاث',
                'category' => 'التقييم والتحسين',
                'type' => 'اختياري',
                'status' => 'implemented',
                'link' => route('admin.reports.export'),
                'link_label' => 'تصدير البيانات',
                'notes' => 'تصدير CSV/JSON للبيانات المفتوحة',
            ],
        ];
    }
}
